name: ttemtoolbox
channels:
  - conda-forge
dependencies:
  - python=3.11.9
  - pandas=2.2.2
  - geopandas=0.14.4
  - openpyxl=3.1.2
  - scipy=1.12.0
  - plotly=5.18.0
  - numpy=1.26.4
  - requests=2.31.0
  - pip 
  - pip:
      - ttemtoolbox
